import { Router } from "express";
import controllerBusRoute from '../controller/busRouteController.js';
const router = Router();
router.get('/getAllRoutes', controllerBusRoute.getAllRoutes);
router.get('/getAllAssignedRoutes', controllerBusRoute.getAllAssignedRoutes);
router.get('/searchRoutes', controllerBusRoute.searchRoutes);
router.post('/addRoute', controllerBusRoute.addRoute);
router.patch('/updateRoute/:id', controllerBusRoute.updateRoute);
router.patch('/updateRouteAndBus/:id', controllerBusRoute.updateRouteAndBus);
router.delete('/deleteRoute/:id', controllerBusRoute.deleteRoute);
router.get('/getRoute/:id', controllerBusRoute.getRouteById);
export default router;